{% set version = "12.6.1" %}

package:
  name: cuda-command-line-tools
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx or ppc64le]

requirements:
  run:
    - cuda-cupti-dev 12.6.68
    # There is no `cuda-gdb` support on Windows so it is skipped.
    # Also `cuda-gdb` should be supported on `ppc64le`, but is currently broken.
    # xref: https://github.com/conda-forge/cuda-command-line-tools-feedstock/issues/6
    - cuda-gdb 12.6.68       # [linux]
    - cuda-nvdisasm 12.6.68
    - cuda-nvprof 12.6.68    # [linux64 or win]
    - cuda-nvtx 12.6.68      # [linux]
    - cuda-sanitizer-api 12.6.68

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing the command line tools to debug CUDA applications
  description: |
    Meta-package containing the command line tools to debug CUDA applications
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
